package com.edu.dao;

import com.edu.pojo.Order;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);
    /**
     * 通过订单号查询订单
     */
    Order findOrderByOrderNo(@Param("orderNo") Long orderNo);
    /**
     * 按照订单号修改
     */
    int   updateByOrderNo(@Param("order")Order order);
    /**
     * 根据订单号和用户号查询订单
     */
    Order findOrderByUserIdAndOrderNo(@Param("userId")Integer userId,@Param("orderNo")Long orderNo);
    /**
     * 根据用户名查询
     */
   List<Order> findOrderByUserId(@Param("userId")Integer userId);

    /**
     * 发货
     */
   int updateOrderSend(Order order);



}