package com.edu.dao;

import com.edu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface    ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Product record);
    /**
     * 根据ID修改status
     */
    int updateStatusById(@Param("id") Integer id,@Param("status") Integer status);
    /**
     * 查询
     */
    List<Product> findProductsByNameAndId(@Param("productId")Integer productId,
                                          @Param("productName")String productName
                                          );

    /**
     * 通过给定的类别ID集合来查询该类的产品
     * @param integers 类别ID集合
     * @param keyword      名字
     * @return
     */
    List<Product> searchProduct(@Param("integerSet")Set<Integer> integers,@Param("keyword") String keyword);

    /**
     * 扣库存
     */
    int reduceProductStock(@Param("productId") Integer productId,@Param("stock") Integer stock);

    /**
     * 是否热销
     */

    List<Product>   selectIsNotHot();
    /**
     * 根据ID和name查询数量
     */
    Integer selectCount(@Param("productId")Integer productId,
                         @Param("productName")String productName);

}